In [ ]:
#!pip install openpyxl

In [2]:
#Import
import pandas as pd
import numpy as np
import scipy
import open3d as o3d

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [3]:
#Display two point cloud with different colours in one o3d window
def display_three_pointclouds(array_1,array_2,array_3,windowname):
    p1_pcd = o3d.geometry.PointCloud()
    p1_pcd.points = o3d.utility.Vector3dVector(array_1)
    p1_pcd.paint_uniform_color([1, 0.706, 0])


    p2_pcd = o3d.geometry.PointCloud()
    p2_pcd.points = o3d.utility.Vector3dVector(array_2)
    p2_pcd.paint_uniform_color([0, 0.706, 1])

    p3_pcd = o3d.geometry.PointCloud()
    p3_pcd.points = o3d.utility.Vector3dVector(array_3)
    p3_pcd.paint_uniform_color([0, 1, 0.706]) 
    
    
    concate_pc = np.concatenate((array_1, array_2,array_3),axis = 0)
    p1_color = np.asarray(p1_pcd.colors)
    p2_color = np.asarray(p2_pcd.colors)
    p3_color = np.asarray(p3_pcd.colors)
    p4_color = np.concatenate((p1_color,p2_color,p3_color), axis=0)

    p4_pcd = o3d.geometry.PointCloud()
    p4_pcd.points = o3d.utility.Vector3dVector(concate_pc)
    p4_pcd.colors = o3d.utility.Vector3dVector(p4_color)
    o3d.visualization.draw_geometries([p4_pcd],window_name = windowname)

In [4]:
def display_two_pointclouds(array_1,array_2,windowname):
    
    p1_pcd = o3d.geometry.PointCloud()
    p1_pcd.points = o3d.utility.Vector3dVector(array_1)
    p1_pcd.paint_uniform_color([1, 0.706, 0])


    p2_pcd = o3d.geometry.PointCloud()
    p2_pcd.points = o3d.utility.Vector3dVector(array_2)
    p2_pcd.paint_uniform_color([0, 0.706, 1])

    
    concate_pc = np.concatenate((array_1, array_2),axis = 0)
    p1_color = np.asarray(p1_pcd.colors)
    p2_color = np.asarray(p2_pcd.colors)

    p4_color = np.concatenate((p1_color,p2_color), axis=0)

    p4_pcd = o3d.geometry.PointCloud()
    p4_pcd.points = o3d.utility.Vector3dVector(concate_pc)
    p4_pcd.colors = o3d.utility.Vector3dVector(p4_color)
    o3d.visualization.draw_geometries([p4_pcd],window_name = windowname)

The purpose of this function is to take a vessel and determine at which axial distance at which another vessel branches off. Additionally it needs to check to see what the terminus condition of the vessel is and then create the appropriate ending conditions for it whether that be flowing directly into another vessel (continous), branching into multiple vessels (split) or no end condition in which case we will need to apply the 0D end condition (tree).

Our first necessary step will be to import the excel file which contains all of the file names and the links between them

In [5]:
#Import Excel Sheets
try:
    arteries_sheet = pd.read_excel('C:\\Users\\Cassidy.Northway\\GitRemoteRepo\\FlowTracker.xlsx', sheet_name = 0)
    veins_sheet = pd.read_excel('C:\\Users\\Cassidy.Northway\\GitRemoteRepo\\FlowTracker.xlsx', sheet_name = 1)
except:
    arteries_sheet = pd.read_excel('C:\\Users\\cbnor\\Documents\\Full Body Flow Model Project\\FlowTracker.xlsx', sheet_name = 0)
    veins_sheet = pd.read_excel('C:\\Users\\cbnor\\Documents\\Full Body Flow Model Project\\FlowTracker.xlsx', sheet_name = 1)
    

In [6]:
#Select sheet
sheet = arteries_sheet
#sheet = veins_sheet

In [7]:
#Define our data frame
df = pd.DataFrame(columns=['Name','Centre Axis Array', 'Radius Array','End Condition'])


In [16]:
#Now we need to define our 
location = 0

#Look at every vessel in the sheet
for index in range(566,567):#range(0,sheet.shape[0]):551,

    name = sheet.at[index,'Anatomy Name']
    file_name = sheet.at[index,'Filename']
    
    #Determine whether the vessel branches at all
    end_point = sheet.at[index,'End Point']

    if pd.isna(end_point):
        final_condition = 'LW' #indicating that the end condition will be the Lax Wendroff
    else:
        #If the branches exist then we need to process the 
        final_condition = end_point.split(',')
        final_condition = [s.strip() for s in final_condition]
    
    #Does the vessel branch (other than the end condition?)
    branches = sheet.at[index,'Out Flow']
    
    if pd.isna(branches):
        segement_tag  = False
    else:
        segement_tag = True
        branches = branches.split(',')
        branches = [s.strip() for s in branches]
        
        #Remove end condition branches 
        if final_condition != 'LW':
            for vessels in final_condition:
                branches.remove(vessels)

    #If there are no segements then we just save the whole thing
    if segement_tag == False:
        main_branch_filename = file_name + '_fitted_data.npy'
    
        try:
            main_branch_array = np.load('C:\\Users\\Cassidy.Northway\\GitRemoteRepo\\FittedVesselsFiles\\' + main_branch_filename)
        except:
            main_branch_array = np.load('C:\\Users\\cbnor\\Documents\\Full Body Flow Model Project\\FittedVesselsFiles\\' + main_branch_filename)
        
        sub_name =  name + '_0'   
        center_sub_array = main_branch_array[:,0:3 ]
        radius_array = main_branch_array[:,3 ]
        end_condition = final_condition
        new_row_seg = {'Name' : sub_name,'Centre Axis Array': center_sub_array, 'Radius Array' : radius_array,'End Condition' : end_condition }
        df.loc[len(df)] = new_row_seg
                
    #If the vessel does segement now we gotta set spicy and determine where it segements for each vessel and which comes first
    if segement_tag == True:
        seg_df = pd.DataFrame(columns=['Branch Name','Index of Split'])
        sub_index = 0
        
        #Find the file names of the main and branches
        main_branch_filename = file_name + '_fitted_data.npy'
        branch_filenames = []

        #For each of the branching files determine the file name to load in the gile
        for i in range(0,len(branches)):
            branch_name = branches[i]
            vessel_row = sheet[sheet['Anatomy Name'].str.match(branch_name)].index.values[0]
            branch_filename = sheet.at[sheet.index[vessel_row],'Filename']
            branch_filename = branch_filename + '_fitted_data.npy'
            branch_filenames.append(branch_filename)

        #Now we import all of the vessel file
        try:
            main_branch_array = np.load('C:\\Users\\Cassidy.Northway\\GitRemoteRepo\\FittedVesselsFiles\\' + main_branch_filename)
        except:
            main_branch_array = np.load('C:\\Users\\cbnor\\Documents\\Full Body Flow Model Project\\FittedVesselsFiles\\' + main_branch_filename)

        for i in range(0,len(branches)):
            branch_filename = branch_filenames[i]
            branch_name = branches[i]
        
            try:
                branch_array = np.load('C:\\Users\\Cassidy.Northway\\GitRemoteRepo\\FittedVesselsFiles\\' + branch_filename)
            except:
                branch_array = np.load('C:\\Users\\cbnor\\Documents\\Full Body Flow Model Project\\FittedVesselsFiles\\' + branch_filename)

            #display_two_pointclouds(main_branch_array[:,0:3],branch_array[:,0:3], branch_name)
            
            #Find the nearest points
            dist_array = scipy.spatial.distance.cdist(main_branch_array[:,0:3],branch_array[:,0:3])
            dist_array = dist_array[:,0]
            index_split = np.where (np.min(dist_array) == dist_array)[0]
            seg_df.loc[len(seg_df)] = {'Branch Name': branch_name , 'Index of Split': index_split[0]}
        
        #We now have the number of off branching vessels and where they branch so now we need to now save the 
        #segements and off branches and sort segment frame by distance along vessel

        seg_df = seg_df.sort_values(by ='Index of Split')
        seg_df = seg_df.reset_index(drop=True)
        intial_index = 0


        for i in range(0,len(seg_df)+1):
            print(i)
            if i != len(seg_df):
                sub_name =  name + '_' + str(i)
                final_index = seg_df.at [ i , 'Index of Split']
                center_sub_array = main_branch_array[intial_index:final_index+1,0:3 ]
                radius_array = main_branch_array[intial_index:final_index,3 ]
                
                p4_pcd = o3d.geometry.PointCloud()
                p4_pcd.points = o3d.utility.Vector3dVector(center_sub_array)
                o3d.visualization.draw_geometries([p4_pcd])
                
                end_condition = [name + '_' + str(i+1), branches[i]+'_0' ]
                new_row_seg = {'Name' : sub_name,'Centre Axis Array': center_sub_array, 'Radius Array' : radius_array,'End Condition' : end_condition }
                if not radius_array.any():
                    print(new_row_seg)
                df.loc[len(df)] = new_row_seg
                intial_index = final_index
                
            else:
                sub_name =  name + '_' + str(i)
                final_index = -1
                center_sub_array = main_branch_array[intial_index:final_index,0:3 ]
                radius_array = main_branch_array[intial_index:final_index,3 ]
                
                p4_pcd = o3d.geometry.PointCloud()
                p4_pcd.points = o3d.utility.Vector3dVector(center_sub_array)
                o3d.visualization.draw_geometries([p4_pcd])
                
                if not radius_array.any():
                    print(new_row_seg)
                if final_condition != 'LW':
                    end_condition = [final_condition[0] +'_0']
                else:
                    end_condition = final_condition
                new_row_seg = {'Name' : sub_name,'Centre Axis Array': center_sub_array, 'Radius Array' : radius_array,'End Condition' : end_condition }
                df.loc[len(df)] = new_row_seg
print(df)    

0
1
2
3
4
5
6
7
{'Name': 'right_leg_artery_6', 'Centre Axis Array': array([[ -151.93245054,   -36.87082269, -1042.78574404],
       [ -151.19531657,   -38.04134096, -1043.16044292],
       [ -150.54909371,   -39.09075997, -1043.47647028],
       [ -150.54909371,   -39.09075997, -1043.47647028],
       [ -149.93567464,   -40.10734042, -1043.76779105],
       [ -149.27033828,   -41.21356635, -1044.08615639],
       [ -148.57976027,   -42.36433561, -1044.41830541],
       [ -147.89061624,   -43.51454602, -1044.75097718],
       [ -147.22958182,   -44.61909543, -1045.07091079],
       [ -146.62333263,   -45.63288167, -1045.36484533],
       [ -146.09854431,   -46.51080259, -1045.61951989],
       [ -145.68189249,   -47.20775601, -1045.82167355],
       [ -145.4000528 ,   -47.67863977, -1045.9580454 ],
       [ -145.4000528 ,   -47.67863977, -1045.9580454 ],
       [ -145.18799216,   -48.0512518 , -1046.15493975],
       [ -144.82472655,   -48.67437225, -1046.47957303],
       [ -144.344967

                  Name                                  Centre Axis Array  \
0   right_leg_artery_0  [[-164.82922560026506, -1.5913713379867038, -1...   
1   right_leg_artery_1  [[-151.93245054142844, -36.87082268629417, -10...   
2   right_leg_artery_2  [[-146.5562614053874, -137.16036328775107, -10...   
3   right_leg_artery_3  [[-113.0959208954924, 55.319743307885524, -620...   
4   right_leg_artery_4  [[-110.89380257984138, 61.41343953450966, -592...   
5   right_leg_artery_5  [[-99.70447157625239, 41.29199109623883, -528....   
6   right_leg_artery_6  [[-96.81111902866166, 35.7518121637611, -510.1...   
7   right_leg_artery_7  [[-74.84672723653887, -41.62993390156622, -153...   
8   right_leg_artery_0  [[-36.524030626727, -12.228601609813062, -64.5...   
9   right_leg_artery_1  [[-74.84672723653887, -41.62993390156622, -153...   
10  right_leg_artery_2  [[-96.81111902866166, 35.7518121637611, -510.1...   
11  right_leg_artery_3  [[-99.70447157625239, 41.29199109623883, -528....   

## Reassess end conditions

We want to go through rows and change the end condition from the name of the vessel segement to the index of those vessels

In [ ]:
#df.to_pickle('rleg.pkl')

In [17]:
#Trouble shooting 

array_1 = main_branch_array[0:50,0:3 ]
array_2 = main_branch_array[51:125,0:3 ]
array_3 = main_branch_array[126:-1,0:3 ]
display_three_pointclouds(array_1,array_2,array_3,'Troubleshoot')

#display_two_pointclouds(df.at[0,'Centre Axis Array'],df.at[1,'Centre Axis Array'],'blarg')


p4_pcd = o3d.geometry.PointCloud()
p4_pcd.points = o3d.utility.Vector3dVector(main_branch_array[0:50,0:3 ])
o3d.visualization.draw_geometries([p4_pcd])

In [12]:
print(main_branch_array[:,0:3])

[[-1.64829226e+02 -1.59137134e+00 -1.03948616e+03]
 [-1.64812181e+02 -2.70416392e+00 -1.03933208e+03]
 [-1.64776860e+02 -3.80097517e-01 -1.03963774e+03]
 ...
 [-3.63007715e+01 -1.22058212e+01 -6.40887592e+01]
 [-3.56097370e+01 -1.22130383e+01 -6.33835880e+01]
 [-3.45768922e+01 -1.22356487e+01 -6.24798714e+01]]
